### ISSUE TITLE
Django admin can't filter orders by organisation

### ISSUE THREAD

**Issue by albinantti** [UTNkar/ordsys#201]
In the django admin interface orders can not be filtered by organisation.

Filtering by any other availible filter works (user, status etc.), but organisation (which calls user__org__id__exact=org_id) returns a bad request (400) error.

**Comment by albinantti** [comment]
If you're working on it, do you think we should overhaul filters in general? For one, in the order items table you can filter order items based on _all_ availible menu items (including those of a different organisation), and filter by order, which makes the filter list consist of 4000 different options, making the page quite tall. 

In general, being able to filter a list based on a different organisations items is a bit dumb since you can't access whatever orders would result anyway

**Comment by chwallen** [comment]
> If you're working on it, do you think we should overhaul filters in general?

Sure! We should probably do some kind of survey and ask people if they use the filter functionality at all, and if so, what filters they use and/or what filters they would like.
